language: python
python:
  - "3.5"
  #- "3.6" 
  # PyPy versions
  - "pypy-5.3.1"

before_install:
 # - mysql -u root -e 'CREATE DATABASE kisschat'
 # - mysql -u root -e 'update mysql.user set password=PASSWORD("matreshka") where User='root';
  - mysql -u root  -e 'CREATE USER 'kiss'@'localhost' IDENTIFIED BY "matreshka"; GRANT ALL PRIVILEGES ON * . * TO 'kiss'@'localhost';'
  - mysql -u kiss -pmatreshka -e 'CREATE DATABASE kisschat'
  - openssl aes-256-cbc -K $encrypted_5cbd2f819ea7_key -iv $encrypted_5cbd2f819ea7_iv -in dd.enc -out dd -d


# command to run tests
script: 
  - pwd
  # Integration testing
#  - mysql -u root
#  - mysql -u root -ppassword
#  - mysql -u root -pletmein
  - ./integration_test.sh
  # - python3 unit_tests.py

# command to install dependencies
install:
  - pip3 install .
  - pip3 install -r requirements.txt
#  - pip3 install tornado
  - sudo -H python setup.py install

after_success:
  - ifconfig
  - echo $test_var
  - ssh -i dd testuser@104.155.104.120
  - pwd
  - ls
#  - kisschat -a 0.0.0.0
