language: python
python:
  - "3.5"
  - "3.6" 
  # PyPy versions
  - "pypy-5.3.1"



# command to run tests
script: 
  - pwd
  # Integration testing
  - kisschat -a 0.0.0.0 &
  - integration_test.sh
  # - python3 unit_tests.py

# command to install dependencies
install:
  - pip3 install .
  - pip3 install -r requirements.txt
#  - pip3 install tornado
  - sudo -H python setup.py install

after_success:
  - ifconfig
#  - kisschat -a 0.0.0.0
